/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 CodeCell3D.gltf 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Model(props) {
  const { scene } = useGLTF("./Codecell3D/CodeCell3D.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <spotLight
        intensity={10}
        angle={Math.PI / 8}
        penumbra={0.15}
        decay={2}
        position={[0.226, 8.749, 0.51]}
        rotation={[-Math.PI / 2, 0, 0]}
        target={nodes.Spot.target}
      >
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.004"]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TubeLeft.geometry}
        material={materials["Material.003"]}
        position={[0.229, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TopOuter.geometry}
        material={materials["Material.003"]}
        position={[0.225, 0.831, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TopInner.geometry}
        material={materials.Black}
        position={[0.225, 0.831, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
      <mesh
        geometry={nodes.MiddleInner.geometry}
        material={materials["Material.003"]}
        position={[0.225, 0.26, 0.492]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
      <mesh
        geometry={nodes.MiddleOuter.geometry}
        material={materials.Black}
        position={[0.225, 0.26, 0.492]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.BottomOuter.geometry}
        material={materials.Black}
        position={[0.225, -0.832, -0.002]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.BottomInner.geometry}
        material={materials["Material.003"]}
        position={[0.225, -0.832, -0.002]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
      <mesh
        geometry={nodes.TubeRight.geometry}
        material={materials.Black}
        position={[0.229, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.CODE.geometry}
        material={materials["Material.002"]}
        position={[0.218, -0.124, 0.372]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.313, 1, 0.313]}
      />
      <mesh
        geometry={nodes.CELL.geometry}
        material={materials["Material.006"]}
        position={[0.218, -0.124, -0.383]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.313, 1, 0.313]}
      />
      <mesh
        geometry={nodes.Tinkers.geometry}
        material={materials.Material}
        position={[0.218, -0.351, -0.001]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.124, 1, 0.124]}
      />
      <mesh
        geometry={nodes.Curve009.geometry}
        material={materials["Material.003"]}
        position={[0.225, -0.259, 0.412]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[4.134, 0, 4.134]}
      />
      <mesh
        geometry={nodes.Curve010.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve011.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve012.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve013.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve014.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve015.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve016.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve017.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve018.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve019.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve020.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve021.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve022.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve023.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve024.geometry}
        material={materials["Material.003"]}
        position={[0.222, -0.618, 0.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.TubeRight001.geometry}
        material={materials["Black.001"]}
        position={[-0.228, 0, 0.014]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TubeLeft001.geometry}
        material={materials["Material.009"]}
        position={[-0.228, 0, 0.014]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TopOuter001.geometry}
        material={materials["Material.009"]}
        position={[-0.224, 0.831, 0.014]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TopInner001.geometry}
        material={materials["Black.001"]}
        position={[-0.224, 0.831, 0.014]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
      <mesh
        geometry={nodes.Tinkers001.geometry}
        material={materials["Material.010"]}
        position={[-0.217, -0.351, 0.015]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.124, 1, 0.124]}
      />
      <mesh
        geometry={nodes.MiddleOuter001.geometry}
        material={materials["Black.001"]}
        position={[-0.224, 0.26, -0.479]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.MiddleInner001.geometry}
        material={materials["Material.009"]}
        position={[-0.224, 0.26, -0.479]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve006.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve008.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve025.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve026.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve027.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve028.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve029.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve030.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve031.geometry}
        material={materials["Material.009"]}
        position={[-0.221, -0.618, -0.807]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[5.933, 0, 5.933]}
      />
      <mesh
        geometry={nodes.Curve032.geometry}
        material={materials["Material.009"]}
        position={[-0.224, -0.259, -0.399]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[4.134, 0, 4.134]}
      />
      <mesh
        geometry={nodes.CODE001.geometry}
        material={materials["Material.011"]}
        position={[-0.217, -0.124, -0.358]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.313, 1, 0.313]}
      />
      <mesh
        geometry={nodes.CELL001.geometry}
        material={materials["Material.012"]}
        position={[-0.217, -0.124, 0.397]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.313, 1, 0.313]}
      />
      <mesh
        geometry={nodes.BottomOuter001.geometry}
        material={materials["Black.001"]}
        position={[-0.225, -0.832, 0.016]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.BottomInner001.geometry}
        material={materials["Material.009"]}
        position={[-0.225, -0.832, 0.016]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.662, 1.312, 0.662]}
      />
    </group>
  );
}

useGLTF.preload("./Codecell3D/CodeCell3D.gltf");
